client:
  order-service:  https://95h0bn0gwk.execute-api.us-east-1.amazonaws.com/dev/v1
  inventory-service: https://v3buu3vqn0.execute-api.us-east-1.amazonaws.com/dev/v1

micronaut:
  application:
    name: core-component
  server:
    port: 8084

