client:
  order-service:  https://gd91qi7qe5.execute-api.us-east-1.amazonaws.com/dev/v1
  inventory-service:   https://d1zuk9f0ob.execute-api.us-east-1.amazonaws.com/dev/v1

micronaut:
  application:
    name: core-component
  server:
    port: 8084

