client:
  order-service:  https://yh1fou2g55.execute-api.us-east-1.amazonaws.com/dev/v1
  inventory-service: https://cky0tief69.execute-api.us-east-1.amazonaws.com/dev/v1

micronaut:
  application:
    name: core-component
  server:
    port: 8084

